---
ansible_port: "{{ sshd_port }}"

# docker_compose_wireguard
wireguard_external_domain: "{{ vault_wireguard_external_domain }}"
wireguard_port: "{{ vault_wireguard_port }}"
wireguard_peers: "{{ vault_wireguard_peers }}"
wireguard_internal_subnet: "{{ vault_wireguard_internal_subnet }}"

sshd_port: "{{ vault_sshd_port }}"
