---
collections:
  - name: community.general
  - name: community.docker
  - name: gluster.gluster
  - name: prometheus.prometheus
  - name: vladgh.samba

roles:
  - name: artis3n.tailscale
  - name: geerlingguy.docker
  - name: geerlingguy.glusterfs
  - name: geerlingguy.nfs
  - name: geerlingguy.node_exporter
  - name: geerlingguy.ntp
  - name: geerlingguy.postfix
  - name: geerlingguy.security
  - name: ironicbadger.proxmox_nag_removal
  - name: ironicbadger.snapraid
  - name: nvidia.nvidia_docker
  - name: nvidia.nvidia_driver
  - name: samdoran.fish
  - name: simoncaron.pve_addons
