---
docker_compose_traefik_version: "3.0"
docker_compose_traefik_log_level: "ERROR"
docker_compose_traefik_enable_dashboard: false
docker_compose_traefik_enable_host_network: false
docker_compose_traefik_enable_access_log: false
docker_compose_traefik_enable_tailscale: false
